FROM docker.pkg.github.com/agilesyndrome/syndromeos-python/python:3.8.1

ARG awscliVersion
ENV AWSCLI_VERSION=${awscliVersion}

RUN curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
&& unzip awscliv2.zip \
&& ./aws/install

