FROM docker.pkg.github.com/agilesyndrome/syndromeos-python/python:3.8.1

ARG toolName
ARG toolVersion
ENV TOOL_NAME=${toolName}
ENV TOOL_VERSION=${toolVersion}

RUN apt-get update \
 && pip3 install --upgrade pip \
 && pip3 install jupyterlab==${TOOL_VERSION} \
 && pip3 install \
      boto==2.49.0 \
      boto3==1.10.49 \
      pandas==0.25.3 \
      numpy==1.18.1 \
      matplotlib==3.1.2

